<application>
    <metadata>
	<title><?= $this->application->title ?></title>
	<?php foreach ($this->stylesheets as $stylesheet) { ?>
	    <stylesheet file="<?= $this->baseUrl ?><?= $stylesheet ?>" />
	<?php } ?>
    </metadata>
    <screen>
	<header>
	    <logo title="<?= $this->application->title ?>" />
	    <topnav>
		<?php if ($this->loggedIn) { ?>
		    <a href="<?= $this->baseUrl ?>/users/<?= strtolower($this->application->user->user_name) ?>">My Account</a> | <a href="<?= $this->baseUrl ?>/authentication/logout">Logout</a>
		<?php } else { ?>
		    <form action="<?= $this->baseUrl ?>/authentication/login" method="post">
			<text label="Username" name="username" id="username" inline="true" />
			<password label="Password" name="password" id="password" inline="true" />
			<submit label="Login" inline="true" />
			<hidden id="controller" value="<?= $this->controller ?>" />
			<hidden id="action" value="<?= $this->action ?>" />
			<?php foreach ($this->request->variables() as $name => $value ) { ?>
			    <hidden id="forward_<?= $name ?>" value="<?= $value ?>" />
			<?php } ?>
		    </form>
		    <?php if ($this->authenticationErrorMessage) { ?>
			<errorbox>
			    <?= $this->authenticationErrorMessage ?>
			</errorbox>
		    <?php } ?>
		<?php } ?>
	    </topnav>
	    <navtabs current="<?= $this->currentTab ?>">
		<?php if (is_array($this->tabs)) { ?>
		    <?php foreach ($this->tabs as $tab) { ?>
			<navtab id="<?= $tab->id ?>" label="<?= $tab->label ?>" url="<?= $this->baseUrl.'/'.$tab->url ?>" />
		    <?php } ?>
		<?php } else { ?>
		    <navtab id="<?= $tabs->id ?>" label="<?= $tabs->label ?>" url="<?= $this->baseUrl.'/'.$tabs->url ?>" />
		<?php } ?>
	    </navtabs>
	</header>
	<content>
	    <?= $this->viewContent ?>
	</content>
    </screen>
</application>