<page>
	<h3><?= $this->tabTitle ?></h3>
	<p><?= $this->tabDescription ?></p>
	<?php if (count($this->filter['filters']) > 0) { ?>
	<filter button="<?= $this->filter['buttonLabel'] ? $this->filter['buttonLabel'] : 'Update' ?>" state="<?= htmlentities($this->listState['filter']) ?>">
		<?php foreach ($this->filter['filters'] as $filter) { ?>
		<filteritem label="<?= $filter['label'] ?>" id="<?= $filter['id'] ?>" type="<?= $filter['input'] ?>" default="<?= $filter['default'] ?>" <?php if (isset($filter['options'])) { ?>options="<?= $this->serializeVariable($filter['options']) ?>"<?php } ?> />
		<?php } ?>
	</filter>
	<?php } ?>
	<?php if (count($this->actions) > 0) { ?>
	<actionbuttons label="Actions">
		<?php foreach ($this->actions as $action) { ?>
			<?php foreach ($action as $link => $label) { ?>
			<listbutton label="<?= $label ?>" link="<?= $this->baseUrl.'/'.$link ?>" />
			<?php } ?>
		<?php } ?>
	</actionbuttons>
	<?php } ?>
	<grid>
		<gridhead>
			<?php foreach($this->grid['headings'] as $heading) { ?>
			<gh <?= ($heading['orderBy'] ? 'order_by="true" order_direction="'.$heading['orderDirection'].'"' : '') ?> <?php if (isset($heading['sortField'])) { ?>link="?filter_orderBy=<?= $heading['sortField'] ?>&filter_orderDirection=<?= (strtoupper($heading['orderDirection']) == 'ASC' ? 'DESC' : 'ASC') ?><?= $this->listState['sort'] ?>"<?php } ?>><?= $heading['label'] ?></gh>
			<?php } ?>
		</gridhead>
	</grid>

	<pre><?= var_dump($this->grid) ?></pre>
</page>