<page>
	<form action="<?= $this->baseUrl ?>/<?= $this->controller ?>/update" method="post">
	<h3><?= $this->actionName ?> <?= $this->entityName ?></h3>
	<?= $this->renderedForm ?>
	<?php if (count($this->actions) > 0) { ?>
	<actionbuttons label="Actions">
		<?php foreach ($this->actions as $action) { ?>
			<?php foreach ($action as $link => $label) { ?>
			<formbutton label="<?= $label ?>" url="<?= $this->baseUrl.'/'.$link ?>" />
			<?php } ?>
		<?php } ?>
	</actionbuttons>
	<?php } ?>
	</form>
</page>